const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.StopAll
	];
};
self.C3_JsPropNameTable = [
	{BG01: 0},
	{Solid: 0},
	{Piso: 0},
	{Obstáculo: 0},
	{Platform: 0},
	{BoundToLayout: 0},
	{Player: 0},
	{Keyboard: 0},
	{txt_menu: 0},
	{txt_menu2: 0},
	{Player_menu: 0},
	{txt_menu3: 0},
	{txt_derrota: 0},
	{txt_derrota2: 0},
	{Player_morto: 0},
	{Sensor: 0},
	{txt_pontos: 0},
	{txt_pontos_derrota: 0},
	{Sons: 0},
	{nuvem: 0},
	{Smoke: 0},
	{Pontos: 0},
	{Pontos_Final: 0}
];

self.InstanceType = {
	BG01: class extends self.ITiledBackgroundInstance {},
	Piso: class extends self.ITiledBackgroundInstance {},
	Obstáculo: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	txt_menu: class extends self.ITextInstance {},
	txt_menu2: class extends self.ITextInstance {},
	Player_menu: class extends self.ISpriteInstance {},
	txt_menu3: class extends self.ITextInstance {},
	txt_derrota: class extends self.ITextInstance {},
	txt_derrota2: class extends self.ITextInstance {},
	Player_morto: class extends self.ISpriteInstance {},
	Sensor: class extends self.ISpriteInstance {},
	txt_pontos: class extends self.ITextInstance {},
	txt_pontos_derrota: class extends self.ITextInstance {},
	Sons: class extends self.IInstance {},
	nuvem: class extends self.ISpriteInstance {},
	Smoke: class extends self.ISpriteInstance {}
}